---
# tasks file for rhel system

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Add InfluxDB GPG key.
  rpm_key:
    key: https://repos.influxdata.com/influxdb.key 
    state: present

- name: Add InfluxDB yum repository
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key

